pipeline {
    agent {
        node {
            label 'jenkins-docker-agent'
        }
    }

    triggers {
        pollSCM('H/5 * * * *')
    }
    
    environment {
        TAG = "v${env.BUILD_NUMBER}"
        IMAGE = "hadyaziz05/frontend:${TAG}"
        DOCKER_HOST = 'tcp://docker-socat:2375'
    }

    stages {
        stage('Build') {
            steps {
                echo "Building Docker Image: ${IMAGE}"
                sh 'docker build -t $IMAGE frontend/'
            }
        }

        stage('Test') {
            steps {
                echo "Running container smoke test..."
                sh 'docker run --rm $IMAGE serve --version'
            }
        }

        stage('Push Image') {
            steps {
                echo "Pushing image to Docker Hub..."
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh '''
                    echo "$PASS" | docker login -u "$USER" --password-stdin
                    docker push $IMAGE
                    '''
                }
            }
        }

        stage('Update Infra Repo') {
            steps {
                echo "Updating infra repo with new image tag..."
                withCredentials([usernamePassword(credentialsId: 'github-creds', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASS')]) {
                    sh '''
                    rm -rf microservices-devops-infra
                    git config --global user.name "Jenkins CI"
                    git config --global user.email "jenkins@example.com"

                    git clone https://$GIT_USER:$GIT_PASS@github.com/Hadyaziz05/microservices-devops-infra.git microservices-devops-infra
                    cd microservices-devops-infra

                    YAML_PATH=k8s/frontend-deployment.yaml
                    sed -i "s|image: .*|image: hadyaziz05/frontend:${TAG}|" "$YAML_PATH"

                    git add "$YAML_PATH"
                    git commit -m "chore: update frontend image to ${TAG}" || echo "No changes"
                    git push origin main
                    '''
                }
            }
        }

        stage('Deploy to K8s') {
            steps {
                echo "Deploying from infra repo..."
                withCredentials([file(credentialsId: 'kube-config-jenkins', variable: 'KUBECONFIG')]) {
                    sh '''
                    cd infra-repo
                    kubectl apply -f k8s/frontend-deployment.yaml
                    '''
                }
            }
        }
    }
}
