apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3030           # Exposed port
      targetPort: 3000   # Port inside the container
  type: ClusterIP         
