apiVersion: v1
kind: Service
metadata:
  name: user-clusterip
  labels:
    app: user    
spec:
  selector:
    app: user
    version: blue
  ports:
  - name: http
    protocol: TCP
    port: 4040
    targetPort: 4000
  type: ClusterIP
