apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-blue
  labels:
    app: user
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
      version: blue
  template:
    metadata:
      labels:
        app: user
        version: blue
    spec:
      containers:
        - name: user-service
          image: hadyaziz05/user-service:v2
          ports:
            - containerPort: 4000   
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGODB_URI
